from __future__ import annotations

import json

from monolith.core.models import HandshakeRecipe, HandshakeStep


WARNING = """# WARNING:
# This code was generated by Monolith from a handshake test.
# It may not work as intended without developer review.
# Captured selectors, coordinates, UIA object properties, or terminal positions
# may fail if the application state changes.
# The user may have already been logged in during testing.
# Developer should validate and update selectors, waits, login flow,
# terminal session handling, error handling, and object targeting.
"""


def generate_code(recipe: HandshakeRecipe) -> str:
    if recipe.target_type == "Website":
        return _website_code(recipe)
    if recipe.target_type == "Desktop Application":
        return _desktop_code(recipe)
    return _terminal_code(recipe)


def _selector(step: HandshakeStep) -> str:
    meta = step.captured_target.metadata if step.captured_target else {}
    return meta.get("css_selector") or meta.get("xpath") or ""


def _website_code(recipe: HandshakeRecipe) -> str:
    url = recipe.notes[0] if recipe.notes else "https://example.com"
    lines = [
        WARNING,
        "from playwright.sync_api import sync_playwright",
        "",
        "",
        "def run_handshake():",
        "    with sync_playwright() as p:",
        "        browser = p.chromium.launch(headless=False)",
        "        page = browser.new_page()",
        "",
        "        # TODO: Developer should update this URL and login flow if needed.",
        f"        page.goto({url!r})",
        "",
    ]
    for step in recipe.steps:
        selector = _selector(step)
        meta = step.captured_target.metadata if step.captured_target else {}
        lines.append(f"        # Step {step.step_number}: {step.action} captured element.")
        lines.append(f"        # Captured target metadata: {json.dumps(meta, ensure_ascii=False)}")
        if step.action == "Click":
            lines.append(f"        page.locator({selector!r}).click()")
        elif step.action == "Type":
            lines.append(f"        page.locator({selector!r}).fill({step.sample_input!r})")
        else:
            lines.append(f"        extracted_text_{step.step_number} = page.locator({selector!r}).inner_text()")
            lines.append(f"        print('Step {step.step_number} extracted text:', extracted_text_{step.step_number})")
        lines.append("")
    lines.extend(["        browser.close()", "", "", "if __name__ == \"__main__\":", "    run_handshake()", ""])
    return "\n".join(lines)


def _desktop_code(recipe: HandshakeRecipe) -> str:
    window_title = "Target Application"
    for step in recipe.steps:
        if step.captured_target and step.captured_target.metadata.get("window_title"):
            window_title = step.captured_target.metadata["window_title"]
            break
    lines = [
        WARNING,
        "from pywinauto import Desktop",
        "",
        "",
        "def run_handshake():",
        "    # TODO: Developer should validate target window title.",
        f"    app_window = Desktop(backend='uia').window(title_re={('.*' + window_title + '.*')!r})",
        "    app_window.set_focus()",
        "",
    ]
    for step in recipe.steps:
        meta = step.captured_target.metadata if step.captured_target else {}
        name = meta.get("name") or meta.get("automation_id") or ""
        control_type = meta.get("control_type") or ""
        lines.append(f"    # Step {step.step_number}: {step.action}.")
        lines.append(f"    # Captured UIA metadata: {json.dumps(meta, ensure_ascii=False)}")
        locator = f"title={name!r}, control_type={control_type!r}" if name and control_type else ""
        if step.action == "Click":
            lines.extend(
                [
                    "    try:",
                    f"        target = app_window.child_window({locator})" if locator else "        target = app_window",
                    "        target.invoke()",
                    "    except Exception:",
                    "        # Fallback only for developer review.",
                    "        target.click_input()",
                ]
            )
        elif step.action == "Type":
            lines.extend(
                [
                    f"    sample_input = {step.sample_input!r}",
                    "    edit_controls = app_window.descendants(control_type='Edit')",
                    "    edit_controls_sorted = sorted(edit_controls, key=lambda c: (c.rectangle().top, c.rectangle().left))",
                    "    for edit in edit_controls_sorted:",
                    "        try:",
                    "            existing_value = edit.get_value()",
                    "        except Exception:",
                    "            existing_value = ''",
                    "        if existing_value.strip():",
                    "            continue",
                    "        try:",
                    "            edit.set_edit_text(sample_input)",
                    "        except Exception:",
                    "            edit.click_input()",
                    "            edit.type_keys(sample_input, with_spaces=True)",
                    "        break",
                ]
            )
        else:
            lines.extend(
                [
                    "    # Manual check required if UI Automation cannot read this control.",
                    "    try:",
                    f"        target = app_window.child_window({locator})" if locator else "        target = app_window",
                    "        print('Extracted text:', target.window_text())",
                    "    except Exception:",
                    "        print('Manual check required: UI Automation could not read this control.')",
                ]
            )
        lines.append("")
    lines.extend(["", "if __name__ == \"__main__\":", "    run_handshake()", ""])
    return "\n".join(lines)


def _terminal_code(recipe: HandshakeRecipe) -> str:
    lines = [
        WARNING,
        "",
        "def run_handshake():",
        f"    # TODO: Developer should connect using detected adapter: {recipe.adapter or 'Manual'}",
        "",
    ]
    for step in recipe.steps:
        meta = step.captured_target.metadata if step.captured_target else {}
        lines.append(f"    # Step {step.step_number}: {step.action}.")
        lines.append(f"    # Captured terminal metadata: {json.dumps(meta, ensure_ascii=False)}")
        if step.action == "Click":
            lines.append(f"    print('TODO: Send terminal key/action: {meta.get('terminal_action', 'ENTER/PF key')}')")
        elif step.action == "Type":
            lines.append(
                f"    print('TODO: Move cursor to row {meta.get('row', '?')}, column {meta.get('column', '?')} and type {step.sample_input}')"
            )
        else:
            lines.append(
                f"    print('TODO: Read {meta.get('length', '?')} characters from row {meta.get('row', '?')}, column {meta.get('column', '?')}')"
            )
        lines.append("")
    lines.extend(["", "if __name__ == \"__main__\":", "    run_handshake()", ""])
    return "\n".join(lines)
